steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "portfolio"
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    dir: "portfolio"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/portfolio-417115/cloud-run-source-deploy/portfolio",
        ".",
      ]
    dir: "portfolio"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/portfolio-417115/cloud-run-source-deploy/portfolio",
      ]
    dir: "portfolio"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "portfolio"
      - "--image"
      - "europe-west1-docker.pkg.dev/portfolio-417115/cloud-run-source-deploy/portfolio"
      - "--region"
      - "europe-west1"
      - "--set-secrets=MY_EMAIL=MY_EMAIL:latest"
      - "--set-secrets=MY_PASSWORD=MY_PASSWORD:latest"
    dir: "portfolio"
options:
  logging: CLOUD_LOGGING_ONLY
