export const skills = [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "TypeScript",
    "Node.js",
    "Next.js",
    "Tailwind CSS",
    "Express.js",
    "Vite",
    "API Integration",
    "RESTful API",
    "Google Cloud Platform",
    "Microsoft Entra ID",
    "Docker",
    "CI/CD",
    "Version Control",
    "Git",
    "Communication",
    "Adaptability",
    "Customer Service",
    "Customer Relationship Management",
    "Team Collaboration",
    "Conflict Resolution",
    "Sales Optimization",
];